version: "3"
services:
  web:
    image: oxxbachelor.azurecr.io/gamification-codecompiler-web
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    restart: always
